title: "Projects"
url: "https://projects.kemitchell.com"
homepage: "https://indieopensource.com"
repository: "kemitchell/projects.kemitchell.com"
repository_url: "https://github.com/kemitchell/projects.kemitchell.com"
collections:
  projects:
    output: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
- newproject
- deploy
